# Generated by Django 3.2.8 on 2021-11-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='my name', max_length=60)),
                ('surname', models.CharField(default='my surname', max_length=60)),
                ('nickname', models.CharField(default='@my_nick', max_length=60, unique=True)),
                ('mail', models.CharField(default='@my_mail@mail.ru', max_length=60)),
                ('password', models.CharField(default='my_pass', max_length=60)),
            ],
            options={
                'verbose_name': 'Clients',
                'verbose_name_plural': 'Clients on a museum',
            },
        ),
    ]
