# Generated by Django 3.2.8 on 2021-11-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Ivan', max_length=100)),
                ('surname', models.CharField(default='Ivanov', max_length=100)),
                ('patronymic', models.CharField(default='Ivanovich', max_length=100)),
                ('date_of_birth', models.DateField()),
                ('post', models.CharField(default='post', max_length=60)),
                ('salary', models.IntegerField(default=0)),
                ('start_working', models.DateField()),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee on a museum',
            },
        ),
    ]
