# Generated by Django 3.2.8 on 2021-11-02 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_id', models.IntegerField(default=0)),
                ('mark', models.IntegerField(default=5)),
                ('description', models.TextField(default='my text about this service')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musem.client')),
            ],
        ),
    ]
