# Generated by Django 3.2.8 on 2021-11-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='client_id',
            new_name='client',
        ),
    ]
