# Generated by Django 3.2.8 on 2021-11-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0007_remove_service_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musem.service'),
        ),
    ]
