# Generated by Django 3.2.8 on 2021-11-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0009_rename_service_id_rating_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('revenue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musem.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musem.service')),
            ],
            options={
                'verbose_name': 'Revenue',
                'verbose_name_plural': 'Revenue in the museum',
            },
        ),
    ]
