# Generated by Django 3.2.8 on 2021-11-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0010_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='revenue',
            field=models.FloatField(default=0.0),
        ),
    ]
