# Generated by Django 3.2.8 on 2021-11-02 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0012_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musem.revenue')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Session on the museum',
            },
        ),
    ]
