# Generated by Django 3.2.8 on 2021-11-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0013_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gik',
            fields=[
                ('gik_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('count_objects', models.IntegerField(default=0)),
                ('material', models.CharField(max_length=20)),
                ('safety_on_coming', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('note', models.TextField(default='Some note')),
            ],
            options={
                'verbose_name': 'Gik',
                'verbose_name_plural': 'Gik in museum',
            },
        ),
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('safe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('safety', models.CharField(max_length=20)),
                ('note', models.TextField()),
                ('gik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musem.gik')),
            ],
            options={
                'verbose_name': 'Safety',
                'verbose_name_plural': 'Safety in a museum',
            },
        ),
    ]
