# Generated by Django 3.2.8 on 2021-11-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0014_gik_safety'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rack_number', models.IntegerField(default=0)),
                ('shelf_number', models.IntegerField(default=0)),
                ('count_at_place', models.IntegerField(default=0)),
                ('gik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musem.gik')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Location on a museum',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('long_description', models.TextField()),
                ('gik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musem.gik')),
            ],
            options={
                'verbose_name': 'Inventory journal',
                'verbose_name_plural': 'Inventory journal in the museum',
            },
        ),
    ]
