# Generated by Django 3.2.8 on 2021-11-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0018_gik_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gik',
            name='employee',
        ),
    ]
