# Generated by Django 3.2.8 on 2021-11-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0020_gik_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_banned',
            field=models.IntegerField(default=1),
        ),
    ]
