# Generated by Django 3.2.8 on 2021-11-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0022_auto_20211102_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
