# Generated by Django 3.2.8 on 2021-11-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0024_auto_20211102_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
