# Generated by Django 3.2.8 on 2021-11-02 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0025_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sal_emp',
            fields=[
                ('salary_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('count_money', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musem.employee')),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salary in the museum',
            },
        ),
    ]
