# Generated by Django 3.2.8 on 2021-11-03 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0027_auto_20211102_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_off',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 3, 8, 0, 2, 514150)),
        ),
    ]
