# Generated by Django 3.2.8 on 2021-11-03 08:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0028_employee_date_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_off',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 3, 8, 0, 22, 102878, tzinfo=utc)),
        ),
    ]
