# Generated by Django 3.2.8 on 2021-11-06 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0032_auto_20211103_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date_writing',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 6, 14, 29, 40, 461063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_off',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 6, 14, 29, 40, 460792, tzinfo=utc)),
        ),
    ]
