# Generated by Django 3.2.9 on 2021-11-14 15:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musem', '0034_auto_20211106_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_off',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 14, 15, 20, 5, 690354, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, default='Ivan', max_length=100),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_writing',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 15, 20, 5, 690880, tzinfo=utc)),
        ),
    ]
